/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BusinessRuleEngine;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.mockito.Mockito.*;


public class AppTest {

    @Test
    public void executeAnActionWithFacts() {
        final Action mockAction = mock(Action.class);
        final Facts mockFacts = mock(Facts.class);
        final RuleEngine businessRuleEngine = new RuleEngine(mockFacts);
        businessRuleEngine.addAction(mockAction);
        businessRuleEngine.run();

        verify(mockAction).execute(mockFacts);
    }
}
