/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BusinessRuleEngine;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.mockito.Mockito.*;


public class AppTest {
    @Test public void NoRulesInitially() {
        final RuleEngine businessRuleEngine = new RuleEngine();
        assertEquals(0, businessRuleEngine.count());
    }

    @Test public void AddTwoActions() {
        final RuleEngine businessRuleEngine = new RuleEngine();
        businessRuleEngine.addAction(() -> {});
        businessRuleEngine.addAction(() -> {});
        assertEquals(2, businessRuleEngine.count());
    }

    @Test public void ExecuteOneAciton() {
        final RuleEngine businessRuleEngine = new RuleEngine();
        final Action mockAction = mock(Action.class);

        businessRuleEngine.addAction(mockAction);
        businessRuleEngine.run();

        verify(mockAction).execute();
    }
}
